[build-system]
requires = ["setuptools"] 
build-backend = "setuptools.build_meta"

[project]
name = "simplepower"
version = "0.0.1"
requires-python = ">=3.10.0"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib", 
    "openpyxl"
]
